[project]
name = "msreport"
description = "Post processing and analysis of quantitative proteomics data"
readme = "README.md"
license = "Apache-2.0"
authors = [
  { name = "David M. Hollenstein", email = "hollenstein.david@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]
keywords = [
  "mass spectrometry",
  "proteomics",
  "post processing",
  "data analysis",
]
requires-python = ">= 3.11"
dependencies = [
  "adjustText >= 0.7.0, < 1.0.0",
  "matplotlib >= 3.8.0",
  "numpy >= 1.26.0",
  "pandas >= 2.1.0, < 3.0.0",
  "profasta >= 0.0.4",
  "pyteomics >= 4.7.0",
  "pyyaml >= 6.0.1",
  "scikit-learn >= 1.2.0",
  "scipy >= 1.16.0",
  "seaborn >= 0.13.0",
  "statsmodels >= 0.14.0",
  "typing_extensions >= 4.4.0",
]
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/hollenstein/msreport"
documentation = "https://hollenstein.github.io/msreport/"
changelog = "https://github.com/hollenstein/msreport/blob/main/CHANGELOG.md"

[project.optional-dependencies]
R = [
    "rpy2>=3.5.3,<3.5.13",
]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.5",
]
docs = [
    "mkdocs-awesome-nav>=3.1.2",
    "mkdocs-macros-plugin>=1.3.7",
    "mkdocs-material>=9.6.15",
    "mkdocs-roamlinks-plugin>=0.3.2",
    "mkdocstrings-python>=1.16.12",
    "ruff>=0.12.2",
]
test = [
    "pytest>=8.3.5",
]

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["msreport"]

[tool.hatch.build.targets.sdist]
include = [
    "msreport",
    "tests",
    "CHANGELOG.md",
    "README.md",
    "LICENSE.txt",
]

[tool.hatch.version]
path = "msreport/__init__.py"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "W", "C", "B"]
ignore = ["B905", "C901"]
unfixable = ["F401"]  # Disable fix for unused imports (`F401`).

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[[tool.mypy.overrides]]
module = [
  "adjustText.*",
  "numpy.*",
  "pandas.*",
  "profasta.*",
  "pyteomics.*",
  "scipy.*",
  "seaborn.*",
  "sklearn.*",
  "statsmodels.*",
  "yaml.*",
]
follow_untyped_imports = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL"
testpaths = [
    "tests",
    "msreport",
]
